### ISSUE TITLE
IE11 - ngxSlickItem not interpreted

### ISSUE THREAD

**Issue by itanex** [devmark/ngx-slick#42]
**Versions**
* ngx-slick: 0.2.1
* slick:  1.9.0 ~~1.5.9~~

**Issue**
The ngxSlickItem does not get interpreted. The width calc occurs, but no content and none of the accessibility attributes are applied (role, aria-*) and none of the included content for the item is placed in the item node.

This only occurs on IE11 (go figure) and it works in Chrome, Safari, Firefox and Edge.

**Question**
What could the issue be? I am at a loss as there are no errors reported into the console.

**Comment by Roelensdam** [comment]
I'm having the same issue. The ngxSlickItem doesn't show up on IE. On the other hand, i can see the dots and when inspecting the html code, and i can see all my items. Those items have a with of 1px and no height.

I'm going to investigate this today, as i need to make it work on Angular6 and IE.

EDIT : ngx-slick : 0.2.1 and Angular 6.1.7

**Comment by Roelensdam** [comment]
UPDATE : It seems to be an error with Angular and IE.
I've updated slick.js to 1.81 and tried it in IE.

Got this error stack ;
`
"Error: Argument non valide.

   at DefaultDomRenderer2.prototype.setValue (http://localhost:4200/vendor.js:117318:67)
   at DebugRenderer2.prototype.setValue (http://localhost:4200/vendor.js:65946:62)
   at checkAndUpdateTextInline (http://localhost:4200/vendor.js:64536:5)
   at checkAndUpdateNodeInline (http://localhost:4200/vendor.js:64933:9)
   at checkAndUpdateNode (http://localhost:4200/vendor.js:64897:5)
   at debugCheckAndUpdateNode (http://localhost:4200/vendor.js:65530:1)
   at debugCheckRenderNodeFn (http://localhost:4200/vendor.js:65516:9)
   at Anonymous function (Function code:134:5)
   at debugUpdateRenderer (http://localhost:4200/vendor.js:65508:1)
   at checkAndUpdateView (http://localhost:4200/vendor.js:64884:1)"
`

vendor.js line 117318 : 
`DefaultDomRenderer2.prototype.setValue = function (node, value) { node.nodeValue = value; };`

Any ideas ?

**Comment by itanex** [comment]
I didn't try 1.8.1, i bumped straight to @latest (1.9.0) which caused the ngx-slick to break down and scream. I created a fail-over experience which doesn't use a carousel, but I may be revisiting this soon. I will give 1.8.1 a try.

**Comment by apexinfosys** [comment]
I have resolved this issue by coping old version files in my new website Angular 6.1 
Old version has javascript with this link https://unpkg.com/slick-carousel@1.6.0/slick/slick.js

I just rename the latest version and added old folder in node package folder and this works for me, I hope this help to anyone.

**Comment by denispodtykan** [comment]
I also had a problem displaying slides in ie 11, started using [https://www.npmjs.com/package/ngx-slick-carousel](https://www.npmjs.com/package/ngx-slick-carousel) - everything is ok

**Comment by lems3** [comment]
I first put a 👍  on @denispodtykan comment, but then removed it. ngx-slick-carousel has it's own load of issues, for us they are a dealbreaker and are pushing us back in ngx-slick.

Each situation is different though, so I'd recommend people to test each solution properly and take the one that fit their need.

**Comment by lems3** [comment]
https://github.com/devmark/ngx-slick/issues/39

This is linked to this issue. I manually updated my files in the node_modules directory for a quick test and it worked. I'll submit a PR for this.

**Comment by lems3** [comment]
See https://github.com/devmark/ngx-slick/pull/58
